from __future__ import annotations

from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DOC = BASE_DIR / "FirstBank_Senegal_Deployment_Security_Package.docx"
GEN_AT = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def set_page(doc: Document) -> None:
    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    normal = doc.styles["Normal"]
    normal.font.name = "Arial"
    normal.font.size = Pt(10.5)

    for style_name in ["Title", "Subtitle", "Heading 1", "Heading 2", "Heading 3"]:
        if style_name in doc.styles:
            style = doc.styles[style_name]
            style.font.name = "Arial"


def p(doc: Document, text: str = "", bold: bool = False, italic: bool = False, align=None, size=None):
    para = doc.add_paragraph()
    if align is not None:
        para.alignment = align
    run = para.add_run(text)
    run.bold = bold
    run.italic = italic
    if size is not None:
        run.font.size = Pt(size)
    return para


def heading(doc: Document, text: str, level: int = 1) -> None:
    doc.add_heading(text, level=level)


def add_bullets(doc: Document, items: list[str]) -> None:
    for item in items:
        doc.add_paragraph(item, style="List Bullet")


def add_table(doc: Document, headers: list[str], rows: list[list[str]]) -> None:
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for i, title in enumerate(headers):
        hdr[i].text = title

    for row_values in rows:
        row = table.add_row().cells
        for i, value in enumerate(row_values):
            row[i].text = value


def add_cover(doc: Document) -> None:
    p(doc, "FirstBank of Nigeria - Internal Use Only", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    p(doc, "")
    p(
        doc,
        "DEPLOYMENT SECURITY PACKAGE",
        bold=True,
        align=WD_ALIGN_PARAGRAPH.CENTER,
        size=16,
    )
    p(
        doc,
        "Project: FirstBank Senegal WhatsApp AI Assistant Platform",
        align=WD_ALIGN_PARAGRAPH.CENTER,
    )
    p(
        doc,
        "Repository: firstbank-mail/senegal",
        align=WD_ALIGN_PARAGRAPH.CENTER,
    )
    p(
        doc,
        "Purpose: Deployment readiness evidence for security and operations officers",
        align=WD_ALIGN_PARAGRAPH.CENTER,
    )
    p(doc, "")

    metadata = [
        ("Generated At", GEN_AT),
        ("Generated By", "GitHub Copilot"),
        ("Document Type", "Deployment Security Package"),
        ("Scope", "Application/API layer, operational logging, audit evidence model"),
        ("State", "Draft for deployment review"),
    ]

    for label, value in metadata:
        p(doc, label, bold=True)
        p(doc, value)
        p(doc, "")


def build() -> None:
    doc = Document()
    set_page(doc)
    add_cover(doc)

    heading(doc, "Table of Contents", 1)
    add_bullets(
        doc,
        [
            "1. Background and Scope",
            "2. Architecture and Runtime Surfaces",
            "3. Security Control Posture",
            "4. Deployment Security Checklist",
            "5. Sample Audit Logs",
            "6. Sample Application Logs",
            "7. Logging and Audit Gaps with Mitigations",
            "8. Source Evidence Reviewed",
        ],
    )

    heading(doc, "1. Background and Scope", 1)
    doc.add_paragraph(
        "This package provides deployment-focused security evidence for the Senegal WhatsApp AI assistant implementation. "
        "It is designed for deployment officers who need a consolidated view of exposed interfaces, implemented controls, "
        "operational logging behavior, sample audit records, and residual risk areas requiring operational controls."
    )
    doc.add_paragraph(
        "The analysis is based on application source code, route definitions, service-layer data writes, and startup/database "
        "initialization scripts in the firstbank-mail/senegal project."
    )

    heading(doc, "1.1 In-Scope Components", 2)
    add_bullets(
        doc,
        [
            "Express API runtime in src/index.ts (webhook, admin, survey, escalation, chat-history, health routes)",
            "Webhook router and handlers in src/webhook/router.ts and src/handlers/*.ts",
            "WhatsApp outbound integration in src/whatsapp-client.ts",
            "Escalation and chat-history persistence services in src/services/*.ts",
            "Database schema/migrations in src/db-init.ts",
            "Environment-driven deployment behavior from package scripts and runtime configuration",
        ],
    )

    heading(doc, "1.2 Explicit Out-of-Scope Items", 2)
    add_bullets(
        doc,
        [
            "Network firewall, reverse proxy, WAF, and infrastructure IAM controls outside this repository",
            "Cloud secret manager policy enforcement external to this codebase",
            "SIEM implementation details beyond application log generation points",
            "End-user IAM portal or SSO controls not implemented in this service",
        ],
    )

    heading(doc, "2. Architecture and Runtime Surfaces", 1)
    doc.add_paragraph(
        "The system receives inbound WhatsApp webhook events, routes them through conversation/survey flows, writes conversation "
        "and escalation traces to PostgreSQL, and returns outbound replies via WhatsApp Cloud API. Administrative endpoints provide "
        "survey lifecycle management, escalation operations, and chat-history retrieval."
    )

    heading(doc, "2.1 Deployment Runtime", 2)
    add_table(
        doc,
        ["Component", "Observed Implementation"],
        [
            ["Language/Runtime", "TypeScript on Node.js >= 22.13.0"],
            ["Server", "Express application bootstrapped in src/index.ts"],
            ["AI orchestration", "Mastra agents and workflows"],
            ["Persistence", "PostgreSQL tables for surveys, escalations, chat history, and meta-flow artifacts"],
            ["Primary startup scripts", "pnpm run dev, pnpm build, pnpm run start, pnpm run webhook"],
            ["Ingress interface", "GET/POST /webhook/whatsapp and additional admin routes"],
        ],
    )

    heading(doc, "2.2 Security-Relevant API Surface (Representative)", 2)
    add_table(
        doc,
        ["Domain", "Method", "Route", "Security/Operational Relevance"],
        [
            ["Health", "GET", "/", "Liveness check used by deployment probes"],
            ["Webhook", "GET", "/webhook/whatsapp", "Meta webhook verification using verify token"],
            ["Webhook", "POST", "/webhook/whatsapp", "Primary inbound customer event ingestion"],
            ["Agent Admin", "POST", "/api/agent/chat", "Direct agent test surface"],
            ["Agent Admin", "POST", "/api/agent/reset", "Global memory reset with audit-style log line"],
            ["Survey Admin", "POST", "/admin/survey", "Survey creation with payload validation"],
            ["Survey Admin", "DELETE", "/admin/survey/:surveyId", "Hard deletion of survey artifacts"],
            ["Escalation Admin", "POST", "/admin/escalation/:ticketId/message", "Human outbound message into customer thread"],
            ["Escalation Admin", "POST", "/admin/escalation/:ticketId/status", "Ticket status transitions"],
            ["Escalation Admin", "DELETE", "/admin/escalation/:ticketId/purge", "Permanent deletion (restricted to completed tickets)"],
            ["Chat History Admin", "GET", "/admin/chat-history/messages", "Operational retrieval of message records"],
            ["Chat History Admin", "GET", "/admin/chat-history/threads", "Thread-level reporting and forensic context"],
        ],
    )

    heading(doc, "3. Security Control Posture", 1)

    heading(doc, "3.1 Input Validation and Data Integrity Controls", 2)
    add_bullets(
        doc,
        [
            "Schema validation implemented on multiple admin routes using zod (example: survey creation, escalation messaging).",
            "Duplicate inbound message suppression implemented with TTL map to reduce replay/retry side effects.",
            "Escalation ticket status constrained to allowed values (pending/completed) before updates.",
            "Direction constraints enforced for escalation message logs (inbound/outbound).",
            "Role constraints enforced for chat history logs (AI/Human/Customer).",
        ],
    )

    heading(doc, "3.2 Authentication/Authorization Observations", 2)
    add_bullets(
        doc,
        [
            "Webhook verification endpoint enforces token comparison for Meta subscription checks.",
            "No uniform route-level admin authentication middleware was observed on /admin/* and /api/agent/* routes in the analyzed code.",
            "No in-code RBAC enforcement was observed for escalation/survey mutation routes.",
            "Deployment should place admin/API routes behind network or gateway-level access controls before production exposure.",
        ],
    )

    heading(doc, "3.3 Data Persistence and Forensic Coverage", 2)
    add_bullets(
        doc,
        [
            "chat_history table captures thread_id, role, message_text, escalation reference, source_message_id, channel, metadata, timestamp.",
            "escalation_messages table captures direction, message content, customer phone, and source message IDs.",
            "escalations table tracks handoff state, human engagement marker, and archival status.",
            "survey and meta-flow tables retain survey configuration and response payloads useful for post-incident analysis.",
        ],
    )

    heading(doc, "3.4 Cryptography and Secrets Handling (Observed)", 2)
    add_bullets(
        doc,
        [
            "Meta Flow encrypted payload decryption logic is present in webhook router path.",
            "Webhook verification token is consumed from environment variables.",
            "WhatsApp API authorization values are redacted in some outbound request logs.",
            "Deployment must ensure .env secrets are injected through secure secret management and not baked into artifacts.",
        ],
    )

    heading(doc, "4. Deployment Security Checklist", 1)
    add_table(
        doc,
        ["Control Area", "Checklist Item", "Status for Go-Live"],
        [
            ["Network Exposure", "Restrict /admin/* and /api/agent/* routes behind VPN, IP allowlist, or API gateway auth", "Required"],
            ["Secrets", "Store WHATSAPP_VERIFY_TOKEN and API credentials in managed secret store", "Required"],
            ["Transport", "TLS termination with valid certificate for webhook and admin routes", "Required"],
            ["Logging", "Forward stdout/stderr to centralized logging with retention >= policy baseline", "Required"],
            ["Audit", "Implement append-only admin action audit sink (or database audit trigger)", "Recommended"],
            ["Monitoring", "Add alert rules for webhook 5xx spikes and escalation route failures", "Required"],
            ["Backups", "Back up PostgreSQL before schema or release changes", "Required"],
            ["Data Minimization", "Mask/redact phone numbers where full value is not operationally necessary", "Recommended"],
        ],
    )

    heading(doc, "5. Sample Audit Logs", 1)
    doc.add_paragraph(
        "The project contains an explicit [AUDIT] style log for memory reset and durable DB records for escalation/chat events. "
        "The following sample audit records are deployment-officer friendly synthesized examples aligned to existing code paths and table writes."
    )

    add_table(
        doc,
        ["Timestamp (UTC)", "Actor", "Action", "Target", "Outcome", "Detail"],
        [
            [
                "2026-07-07T08:10:02Z",
                "system",
                "WEBHOOK_VERIFIED",
                "GET /webhook/whatsapp",
                "SUCCESS",
                "Meta subscription verification token accepted",
            ],
            [
                "2026-07-07T08:11:17Z",
                "webhook.processor",
                "INBOUND_MESSAGE_ACCEPTED",
                "POST /webhook/whatsapp",
                "SUCCESS",
                "Inbound message routed to engagement flow; message id wamid.HBgMNT...",
            ],
            [
                "2026-07-07T08:11:31Z",
                "webhook.processor",
                "DUPLICATE_MESSAGE_SUPPRESSED",
                "POST /webhook/whatsapp",
                "SUCCESS",
                "Duplicate inbound message skipped by TTL replay guard",
            ],
            [
                "2026-07-07T08:13:09Z",
                "ai.assistant",
                "ESCALATION_CREATED",
                "escalations.ticket_id=ESC-20260707-0041",
                "SUCCESS",
                "Pending escalation created from customer support conversation",
            ],
            [
                "2026-07-07T08:14:22Z",
                "human.agent",
                "ESCALATION_MESSAGE_SENT",
                "POST /admin/escalation/:ticketId/message",
                "SUCCESS",
                "Outbound human message delivered and persisted to escalation_messages",
            ],
            [
                "2026-07-07T08:17:06Z",
                "support.supervisor",
                "ESCALATION_STATUS_UPDATED",
                "POST /admin/escalation/:ticketId/status",
                "SUCCESS",
                "Ticket status updated from pending to completed",
            ],
            [
                "2026-07-07T08:20:34Z",
                "admin.operator",
                "SURVEY_ARCHIVED",
                "DELETE /admin/survey/:surveyId/archive",
                "SUCCESS",
                "Survey archived with archived_at timestamp",
            ],
            [
                "2026-07-07T08:23:41Z",
                "admin.operator",
                "GLOBAL_MEMORY_RESET",
                "POST /api/agent/reset",
                "SUCCESS",
                "[AUDIT] Global agent memory reset initiated. Cleared 124 conversation threads",
            ],
            [
                "2026-07-07T08:25:49Z",
                "admin.operator",
                "ESCALATION_PURGE_ATTEMPT",
                "DELETE /admin/escalation/:ticketId/purge",
                "FAILURE",
                "Rejected because ticket status was not completed",
            ],
            [
                "2026-07-07T08:26:58Z",
                "meta.flow.handler",
                "NFM_REPLY_SAVED",
                "meta_flow_responses.flow_id=130981723198712",
                "SUCCESS",
                "Decrypted flow payload stored with source=nfm_reply",
            ],
        ],
    )

    heading(doc, "6. Sample Application Logs", 1)
    doc.add_paragraph(
        "This service primarily logs through console output. In production, these lines are typically captured by process managers "
        "(systemd, Docker, PM2, Kubernetes) and then forwarded to a central sink. The lines below mirror observed message patterns."
    )

    app_log_samples = [
        "2026-07-07T08:10:02.112Z INFO WEBHOOK_VERIFIED",
        "2026-07-07T08:11:17.901Z INFO 📩 Incoming message from 221771234567",
        "2026-07-07T08:11:18.034Z INFO Checking session for: 221771234567",
        "2026-07-07T08:11:18.220Z INFO No survey session for 221771234567 Routing to chat handler.",
        "2026-07-07T08:11:18.843Z INFO Chat handler triggered for 221771234567 with text: I need help with my card",
        "2026-07-07T08:11:19.773Z INFO Sending WhatsApp message to 221771234567 with raw reply: I can help with that.",
        "2026-07-07T08:11:24.115Z INFO ↩️ Skipping duplicate inbound message wamid.HBgMNT...",
        "2026-07-07T08:13:09.447Z INFO Human handoff is active for 221771234567 - suppressing automated reply while a human agent owns the conversation.",
        "2026-07-07T08:14:22.667Z INFO WhatsApp API request URL: https://graph.facebook.com/v23.0/111222333/messages",
        "2026-07-07T08:14:23.191Z INFO WhatsApp API response status: 200 OK",
        "2026-07-07T08:16:06.552Z WARN ⚠️ WhatsApp API returned empty body despite 2xx status",
        "2026-07-07T08:17:36.228Z ERROR Failed to log outbound human chat message Error: duplicate key value violates unique constraint",
        "2026-07-07T08:20:49.077Z ERROR ❌ Webhook processing error: Error: DB not initialized",
        "2026-07-07T08:23:41.515Z INFO [AUDIT] Global agent memory reset initiated. Cleared 124 conversation threads at 2026-07-07T08:23:41.515Z",
    ]

    add_table(
        doc,
        ["Sample Log Line", "Interpretation"],
        [
            [app_log_samples[0], "Webhook verification succeeded during subscription check"],
            [app_log_samples[1], "Inbound customer traffic observed at webhook edge"],
            [app_log_samples[4], "Chat handler engaged for customer text message"],
            [app_log_samples[6], "Replay/duplicate suppression activated"],
            [app_log_samples[8], "Outbound request to WhatsApp API initiated"],
            [app_log_samples[10], "Non-fatal API anomaly warning surfaced"],
            [app_log_samples[12], "Critical runtime error that should trigger alerting"],
            [app_log_samples[13], "Administrative memory reset with audit-style marker"],
        ],
    )

    heading(doc, "6.1 Raw Sample Log Bundle", 2)
    for line in app_log_samples:
        doc.add_paragraph(line)

    heading(doc, "7. Logging and Audit Gaps with Mitigations", 1)
    add_table(
        doc,
        ["Observed Gap", "Operational Risk", "Mitigation Recommendation"],
        [
            [
                "No dedicated append-only audit trail for admin route mutations",
                "Administrative actions may be harder to prove for compliance reviews",
                "Add database-backed audit_events table with immutable insert-only policy",
            ],
            [
                "No consistent per-request correlation ID in logs",
                "Cross-service tracing and incident triage becomes slower",
                "Inject correlation/request IDs at middleware and include in all log lines",
            ],
            [
                "Admin surfaces do not show uniform in-code auth middleware",
                "Unauthorized administrative use if endpoint is exposed",
                "Enforce gateway auth + route middleware RBAC before production cutover",
            ],
            [
                "Potential exposure of sensitive runtime details in console logs",
                "PII/secret leakage into centralized logs",
                "Mask phone numbers and remove verbose payload logging in production mode",
            ],
            [
                "Console text logs are not structured JSON by default",
                "SIEM parsing and rule reliability may degrade",
                "Adopt JSON logger with fixed fields (level, service, action, actor, request_id)",
            ],
        ],
    )

    heading(doc, "8. Source Evidence Reviewed", 1)
    add_bullets(
        doc,
        [
            "src/index.ts",
            "src/webhook/router.ts",
            "src/handlers/chat.handler.ts",
            "src/whatsapp-client.ts",
            "src/services/escalation-service.ts",
            "src/services/chat-history-service.ts",
            "src/db-init.ts",
            "package.json",
            ".env (variable usage context only; secrets not reproduced)",
        ],
    )

    doc.add_paragraph("End of document")
    doc.save(OUTPUT_DOC)


if __name__ == "__main__":
    build()
    print(str(OUTPUT_DOC))
